#############################################################################
# Makefile for building: qt_openGL_helloworld.app/Contents/MacOS/qt_openGL_helloworld
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  qt_openGL_helloworld.pro
# Template: app
# Command: /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/qmake -spec macx-xcode -o qt_openGL_helloworld.xcodeproj/project.pbxproj qt_openGL_helloworld.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/qmake
qt_openGL_helloworld.xcodeproj/project.pbxproj: qt_openGL_helloworld.pro /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/qmake.conf /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/spec_pre.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/qdevice.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/device_config.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/shell-unix.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/unix.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/mac.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/gcc-base.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/gcc-base-mac.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/clang.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/clang-mac.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios/clang.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios/qmake.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/qconfig.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_bootstrap.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_core.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_gui.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_network.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_opengl.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_sql.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_testlib.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_widgets.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_xml.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qico.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qios.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_tool_syncqt.pri \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt_functions.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt_config.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/qt_config.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/qmake.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-xcode/qmake.conf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/spec_post.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/exclusive_builds.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/default_pre.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/default_pre.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/default_pre.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/resolve_config.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/default_post.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/sdk.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/default_post.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/objective_c.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/warn_on.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/plugins/platforms/libqios.prl \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/qt.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/resources.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/moc.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/unix/opengl.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/uic.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/unix/thread.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/rez.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/testcase_targets.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/exceptions.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/yacc.prf \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/lex.prf \
		qt_openGL_helloworld.pro \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5PlatformSupport.prl \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Gui.prl \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Core.prl \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5OpenGL.prl \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Widgets.prl
	$(QMAKE) -spec macx-xcode -o qt_openGL_helloworld.xcodeproj/project.pbxproj qt_openGL_helloworld.pro
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/spec_pre.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/qdevice.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/device_config.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/shell-unix.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/unix.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/mac.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/gcc-base.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/gcc-base-mac.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/clang.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/clang-mac.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios/clang.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/common/ios/qmake.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/qconfig.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_bootstrap.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_concurrent.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_core.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_gui.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_network.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_opengl.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_platformsupport.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_printsupport.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_sql.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_testlib.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_widgets.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_lib_xml.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qico.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qios.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/modules/qt_tool_syncqt.pri:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt_functions.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt_config.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/qt_config.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/qmake.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-xcode/qmake.conf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/spec_post.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/exclusive_builds.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/default_pre.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/default_pre.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/default_pre.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/resolve_config.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/default_post.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/sdk.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/default_post.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/objective_c.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/warn_on.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/plugins/platforms/libqios.prl:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/qt.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/features/qt.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/resources.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/moc.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/unix/opengl.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/uic.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/unix/thread.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/mac/rez.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/testcase_targets.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/exceptions.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/yacc.prf:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/features/lex.prf:
qt_openGL_helloworld.pro:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5PlatformSupport.prl:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Gui.prl:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Core.prl:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5OpenGL.prl:
/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o qt_openGL_helloworld.xcodeproj/project.pbxproj qt_openGL_helloworld.pro

qmake_all: FORCE

