#############################################################################
# Makefile for building: qt_openGL_helloworld.app/Contents/MacOS/qt_openGL_helloworld
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  qt_openGL_helloworld.pro
# Template: app
# Command: /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/qmake -spec macx-xcode -o qt_openGL_helloworld.xcodeproj/project.pbxproj qt_openGL_helloworld.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/moc
UIC       = /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DDARWIN_NO_CARBON -DQT_NO_PRINTER -DQT_NO_PRINTDIALOG -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang -I. -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/mkspecs/macx-ios-clang/ios -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtOpenGL -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtWidgets -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtGui -I/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtCore -I. -I.
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: ./moc_xfWidget.cpp ./ui_xfWidget.h
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_xfWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_xfWidget.cpp
moc_xfWidget.cpp: /Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtCore/QtCore \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtGui/QtGui \
		/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/include/QtOpenGL/QtOpenGL \
		xfWidget.h
	/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.0.0 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include xfWidget.h -o moc_xfWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_xfWidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_xfWidget.h
ui_xfWidget.h: xfWidget.ui
	/Users/xiafei/qt_ios_dev/ios_dev/qtbase-ios-iphone/bin/uic xfWidget.ui -o ui_xfWidget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

